Repository 15VuNguyen/skindora, pull requests merged in 2025-05, with the labels that each got.

#3 Thêm compression gzip and zstd vô caddyfile
  .vscode/settings.json
Labels: enhancement

#4 Add zstd encoding support to Caddyfile
  frontend/Caddyfile
Labels: enhancement

#6 feat: Tích hợp định tuyến và cấu trúc layout
  backend/package-lock.json
  backend/package.json
  frontend/.prettierrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Hero.tsx
  frontend/src/components/ProtectedRoute.tsx
  frontend/src/components/Topbar.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/index.css
  frontend/src/layouts/RootLayout.tsx
  frontend/src/pages/Homepage.tsx
  frontend/src/routes/adminRoutes.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/privateRoutes.tsx
  frontend/src/routes/protectedRoutes.tsx
  frontend/src/routes/publicRoutes.tsx
Labels: enhancement

#14 Feature/table
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Table/index.tsx
  frontend/src/components/Typography/index.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/features/Homepage/Adminpage.tsx
  frontend/src/types/api.d.ts
  frontend/src/types/index.ts
Labels: enhancement

#16 Config websocket
  backend/src/index.ts
  backend/src/lib/socket.ts
  backend/src/routes/users.routes.ts
Labels: enhancement

#26 Modified Redis Configuration
  backend/.gitignore
  backend/src/services/redis.services.ts
Labels: config

#32 Feature/config socket events
  backend/src/lib/socket.ts
  backend/src/types/socketTypes.ts
Labels: enhancement

#33 fix: fix redis container can't run
  compose.dev.yaml
Labels: bug

#35 Tái cấu trúc các thành phần HighlightCategories và HighlightProducts …
  .vscode/tasks.json
  frontend/src/features/Homepage/components/HighlightCatagories.tsx
  frontend/src/features/Homepage/components/HighlightProducts.tsx
Labels: enhancement
