Repository 15VuNguyen/skindora, pull requests merged in 2025-07, with the labels that each got.

#111 Feature/cancel-order
  backend/src/constants/messages.ts
  backend/src/controllers/orders.controllers.ts
  backend/src/middlewares/orders.middlewares.ts
  backend/src/models/requests/Orders.requests.ts
  backend/src/models/schemas/Orders/Order.schema.ts
  backend/src/models/schemas/Orders/OrderDetail.schema.ts
  backend/src/routes/orders.routes.ts
  backend/src/services/orders.services.ts
  backend/src/type.d.ts
  backend/src/utils/date.ts
  backend/src/utils/orderStatus.ts
Labels: enhancement

#112 Fix/voucher middleware
  backend/src/constants/messages.ts
  backend/src/controllers/admin.controllers.ts
  backend/src/controllers/payments.controllers.ts
  backend/src/controllers/products.controllers.ts
  backend/src/controllers/voucher.controllers.ts
  backend/src/middlewares/voucher.middlewares.ts
  backend/src/routes/admin.routes.ts
  backend/src/routes/payments.routes.ts
  backend/src/routes/users.routes.ts
  backend/src/services/Payments/vnpay.services.ts
  backend/src/services/Payments/zalopay.services.ts
  backend/src/services/voucher.services.ts
Labels: bug

#114 Define navigation & basic configuration
  mobile/package-lock.json
  mobile/package.json
  mobile/src/api/api.ts
  mobile/src/components/Button.jsx
  mobile/src/constants/colors.ts
  mobile/src/hooks/common/useDelete.ts
  mobile/src/hooks/common/useFetch.ts
  mobile/src/hooks/common/usePost.ts
  mobile/src/hooks/common/usePut.ts
  mobile/src/navigation/AppNavigator.tsx
  mobile/src/navigation/AuthNavigator.tsx
  mobile/src/navigation/HomeNavigator.tsx
  mobile/src/navigation/NotificationNavigator.tsx
  mobile/src/navigation/ProfileNavigator.tsx
  mobile/src/navigation/SearchNavigator.tsx
  mobile/src/screens/Main/CartScreen.tsx
  mobile/src/screens/Main/NotificationScreen.tsx
  mobile/src/screens/Main/ProductDetailScreen.tsx
  mobile/src/screens/Main/ProductListScreen.tsx
  mobile/src/screens/Main/ProfileScreen.tsx
  mobile/src/screens/Main/SearchScreen.tsx
  mobile/src/screens/Main/SettingsScreen.tsx
  mobile/src/types/navigation.ts
Labels: config

#125 Fix get all reviews
  backend/src/controllers/products.controllers.ts
Labels: bug

#128 Feature/manage brand
  frontend/src/features/Admin/BrandDetail.tsx
  frontend/src/features/Admin/CreateBrand.tsx
  frontend/src/features/Admin/UpdateBrand.tsx
  frontend/src/features/Admin/UpdateDetail.tsx
  frontend/src/features/Admin/columns/brandsColumns.tsx
  frontend/src/hooks/Brand/useFetchBrandByID.ts
  frontend/src/lib/brandSchema.ts
  frontend/src/routes/adminRoutes.tsx
Labels: enhancement

#145 Build count order api
  backend/src/constants/messages.ts
  backend/src/controllers/orders.controllers.ts
  backend/src/routes/orders.routes.ts
  backend/src/services/orders.services.ts
Labels: enhancement

#155 Feature/fix ingredient
  frontend/src/api/product.ts
  frontend/src/features/Admin/Product/UpdateDetail.tsx
  frontend/src/features/Admin/components/AddProduct.tsx
  frontend/src/features/Admin/components/ProductOverview.tsx
  frontend/src/features/Staff/ManageOrdersStaff.tsx
  frontend/src/features/Staff/ProductOverviewStaff.tsx
  frontend/src/hooks/Filter/useFetchActiveFilter.ts
  frontend/src/hooks/Filter/useFetchAllFilter.ts
  frontend/src/hooks/Product/useFetchProduct.ts
  frontend/src/lib/productSchema.ts
  frontend/src/types/product.d.ts
Labels: enhancement, ui, refactor

#159 Feature/get all fiter product type
  backend/src/routes/products.routes.ts
Labels: enhancement

#164 Fix/order response
  backend/src/constants/messages.ts
  backend/src/middlewares/orders.middlewares.ts
  backend/src/models/requests/Cart.requests.ts
  backend/src/models/requests/Orders.requests.ts
  backend/src/models/schemas/Orders/Order.schema.ts
  backend/src/routes/orders.routes.ts
  backend/src/services/cart.services.ts
  backend/src/services/orders.services.ts
  backend/src/services/product.services.ts
Labels: enhancement

#168 Feature/payment callback
  backend/src/controllers/payments.controllers.ts
  backend/src/middlewares/orders.middlewares.ts
  backend/src/routes/payments.routes.ts
  backend/src/services/Payments/vnpay.callbacks.ts
  backend/src/services/Payments/vnpay.services.ts
  backend/src/services/Payments/zalopay.callbacks.ts
  backend/src/services/Payments/zalopay.services.ts
Labels: enhancement

#184 Sửa lại trang index admin
  frontend/src/features/Admin/columns/ordersColumns.tsx
  frontend/src/features/Admin/index.tsx
  frontend/src/features/Staff/orderStaffColumn.tsx
Labels: enhancement

#185 Chỉnh lại ui
  frontend/src/features/Admin/DoanhThu/RevenueDashboard.tsx
  frontend/src/features/Admin/DoanhThu/index.tsx
  frontend/src/features/Admin/index.tsx
Labels: enhancement

#186 Sửa lại vài chỗ input
  frontend/src/features/Admin/Brand/CreateBrand.tsx
  frontend/src/features/Admin/Dactinh/CreateDacTinh.tsx
  frontend/src/features/Admin/Size/CreateSize.tsx
Labels: ui

#188 Import MainTabs in root navigation
  mobile/src/navigations/RootNavigation.js
Labels: bug

#189 Develop
  mobile/src/navigations/RootNavigation.js
Labels: bug

#190 Xóa những thứ không cần thiết
  frontend/src/features/Admin/DoanhThu/Custom.tsx
  frontend/src/features/Admin/DoanhThu/RevenueDashboard.tsx
  frontend/src/features/Admin/Origin/ManageOrigin.tsx
  frontend/src/features/Admin/Voucher/ManageVoucher.tsx
  frontend/src/features/Admin/columns/brandsColumns.tsx
  frontend/src/features/Admin/columns/dactinhsColumn.tsx
  frontend/src/features/Admin/columns/ingredientsColumn.tsx
  frontend/src/features/Admin/columns/ordersColumns.tsx
  frontend/src/features/Admin/columns/originColumns.tsx
  frontend/src/features/Admin/columns/productTypeColumns.tsx
  frontend/src/features/Admin/columns/sizeColumns.tsx
  frontend/src/features/Admin/columns/skinTypeColumns.tsx
  frontend/src/features/Admin/columns/usesColumns.tsx
  frontend/src/features/Admin/components/ProductOverview.tsx
  frontend/src/features/Admin/index.tsx
  frontend/src/features/Staff/orderStaffColumn.tsx
Labels: ui, refactor

#194 Chỉnh ui
  frontend/src/features/Admin/Brand/ManageBrand.tsx
  frontend/src/features/Admin/Order/ManageOrders.tsx
  frontend/src/features/Admin/index.tsx
  frontend/src/features/Staff/ManageOrdersStaff.tsx
  frontend/src/features/Staff/ProductOverviewStaff.tsx
Labels: ui
