Repository 15VuNguyen/skindora, pull requests merged in 2025-06, with the labels that each got.

#37 Thêm auth login và signup
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/carousel.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/command.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/sheet.tsx
  frontend/src/components/ui/skeleton.tsx
  frontend/src/components/ui/sonner.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/contexts/AuthContext.tsx
  frontend/src/features/Auth/components/Forms/Login.tsx
  frontend/src/features/Auth/components/Forms/SignUp.tsx
  frontend/src/features/Auth/components/LeftPanel.tsx
  frontend/src/features/Auth/hooks/useAuthSwitcher.tsx
  frontend/src/features/Auth/index.tsx
  frontend/src/features/Auth/pages/LoginPage.tsx
  frontend/src/features/Auth/pages/RegisterPage.tsx
  frontend/src/features/Homepage/components/Hero.tsx
  frontend/src/features/Homepage/components/Topbar.tsx
  frontend/src/features/Homepage/index.tsx
  frontend/src/hooks/use-mobile.ts
  frontend/src/layouts/RootLayout.tsx
  frontend/src/lib/apiClient.ts
  frontend/src/main.tsx
  frontend/src/routes/publicRoutes.tsx
  frontend/src/schemas/authSchemas.ts
  frontend/src/services/authService.ts
  frontend/src/utils/axios/types.ts
  frontend/src/utils/tokenManager.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: enhancement

#51 feat: Payment with zalopay and vnpay, Wish List Flow
  backend/package-lock.json
  backend/package.json
  backend/src/constants/enums.ts
  backend/src/constants/messages.ts
  backend/src/controllers/payments.controller.ts
  backend/src/controllers/products.controller.ts
  backend/src/index.ts
  backend/src/middlewares/users.middlewares.ts
  backend/src/models/schemas/Orders/Order.schema.ts
  backend/src/models/schemas/Orders/OrderDetail.schema.ts
  backend/src/models/schemas/Products/FilterBrand.schema.ts
  backend/src/models/schemas/Products/FilterDacTinh.schema copy.ts
  backend/src/models/schemas/Products/FilterHskIngredient.ts
  backend/src/models/schemas/Products/FilterHskProductType.ts
  backend/src/models/schemas/Products/FilterHskSize.schema copy.ts
  backend/src/models/schemas/Products/FilterHskSkinType.schema copy.ts
  backend/src/models/schemas/Products/FilterHskUses.schema.ts
  backend/src/models/schemas/Products/Product.schema.ts
  backend/src/routes/payments.routes.ts
  backend/src/routes/users.routes.ts
  backend/src/services/Payments/vnpay.service.ts
  backend/src/services/Payments/zalopay.service.ts
  backend/src/services/Products/product.services.ts
  backend/src/services/database.services.ts
  backend/src/utils/otp.ts
Labels: enhancement

#56 docs: Add wish list flow swagger api
  backend/src/openAPI.yml
Labels: documentation

#77 feat: Add send daily email for admin notify product almost out of stock (<=10)
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/services/product.services.ts
  backend/src/services/users.services.ts
  backend/src/utils/cron/email.services.ts
  backend/src/utils/templates/daily-report.html
Labels: enhancement

#81 Fix/refactor order & order detail schema
  backend/src/models/schemas/Orders/Order.schema.ts
  backend/src/models/schemas/Orders/OrderDetail.schema.ts
Labels: config

#80 Feature/order
  backend/src/constants/enums.ts
  backend/src/constants/messages.ts
  backend/src/controllers/cart.controllers.ts
  backend/src/controllers/orders.controllers.ts
  backend/src/index.ts
  backend/src/middlewares/admin.middlewares.ts
  backend/src/middlewares/carts.middlewares.ts
  backend/src/middlewares/orders.middlewares.ts
  backend/src/middlewares/products.middlewares.ts
  backend/src/middlewares/staff.middlewares.ts
  backend/src/models/requests/Cart.requests.ts
  backend/src/models/requests/Orders.requests.ts
  backend/src/routes/cart.routes.ts
  backend/src/routes/orders.routes.ts
  backend/src/services/cart.services.ts
  backend/src/services/orders.services.ts
  backend/src/services/product.services.ts
  backend/src/type.d.ts
  backend/src/utils/orderStatus.ts
Labels: enhancement

#83 Feature/crud product and filters - feat(admin/products): Implement Create New Product functionality
  backend/src/constants/messages.ts
  backend/src/constants/product.ts
  backend/src/controllers/products.controllers.ts
  backend/src/middlewares/admin.middlewares.ts
  backend/src/models/requests/Product.requests.ts
  backend/src/models/schemas/FilterHskOrigin.schema.ts
  backend/src/models/schemas/Product.schema.ts
  backend/src/routes/admin.routes.ts
  backend/src/routes/products.routes.ts
  backend/src/services/database.services.ts
  backend/src/services/filterBrand.services.ts
  backend/src/services/filterDacTinh.services.ts
  backend/src/services/filterHskIngredient.services.ts
  backend/src/services/filterHskProductType.services.ts
  backend/src/services/filterHskSize.services.ts
  backend/src/services/filterHskSkinType.services.ts
  backend/src/services/filterHskUses.services.ts
  backend/src/services/filterOrigin.services.ts
  backend/src/services/product.services.ts
  backend/src/utils/pagination.helper.ts
Labels: bug, enhancement, config

#84 feat: Add Kafka config, Voucher Schema, CRUD voucher for admin with full middlewares
  backend/package-lock.json
  backend/package.json
  backend/src/constants/enums.ts
  backend/src/constants/messages.ts
  backend/src/controllers/admin.controllers.ts
  backend/src/controllers/orders.controllers.ts
  backend/src/controllers/payments.controllers.ts
  backend/src/controllers/products.controllers.ts
  backend/src/controllers/voucher.controllers.ts
  backend/src/index.ts
  backend/src/middlewares/admin.middlewares.ts
  backend/src/middlewares/common.middlewares.ts
  backend/src/middlewares/reviews.middlewares.ts
  backend/src/middlewares/voucher.middlewares.ts
  backend/src/models/requests/Vouchers.request.ts
  backend/src/models/schemas/Voucher.schema.ts
  backend/src/routes/admin.routes.ts
  backend/src/routes/payments.routes.ts
  backend/src/routes/reviews.routes.ts
  backend/src/services/Payments/vnpay.services.ts
  backend/src/services/Payments/zalopay.services.ts
  backend/src/services/database.services.ts
  backend/src/services/kafka.services.ts
  backend/src/services/voucher.services.ts
  backend/src/type.d.ts
  compose.dev.yaml
  frontend/package-lock.json
Labels: enhancement

#90 Làm trang quản lý staff
  frontend/src/api/product.ts
  frontend/src/features/Admin/ManageProduct.tsx
  frontend/src/features/Admin/components/ProductOverview.tsx
  frontend/src/hooks/useFetchOrders.ts
  frontend/src/hooks/useFetchProduct.ts
  frontend/src/services/productService.ts
  frontend/src/types/index.ts
  frontend/src/types/product.d.ts
Labels: enhancement

#96 feat: Add config for kafka in dev, modify getAllVoucher
  backend/src/controllers/voucher.controllers.ts
  backend/src/index.ts
  backend/src/middlewares/error.middlewares.ts
  backend/src/services/Kafka/consumer.ts
  backend/src/services/Kafka/kafka.services.ts
  backend/src/services/voucher.services.ts
  backend/src/utils/pagination.helper.ts
  compose.dev.yaml
Labels: config

#97 Refactor/remove unused default handler
  backend/src/constants/messages.ts
  backend/src/controllers/voucher.controllers.ts
  backend/src/middlewares/error.middlewares.ts
  backend/src/middlewares/voucher.middlewares.ts
  backend/src/routes/admin.routes.ts
  backend/src/routes/users.routes.ts
Labels: refactor
